import type { CaseStudy, JournalPost } from './sanity/queries'

export const mockCaseStudies: CaseStudy[] = [
  {
    _id: 'cs-1',
    title: 'Al Barakeh',
    slug: { current: 'al-barakeh' },
    client: 'Al Barakeh Group',
    category: 'brand-identity',
    year: 2024,
    tagline: 'Rooting heritage in contemporary form.',
    services: ['Brand Strategy', 'Visual Identity', 'Brand Guidelines'],
    featured: true,
    order: 1,
  },
  {
    _id: 'cs-2',
    title: 'Lumière',
    slug: { current: 'lumiere' },
    client: 'Lumière Hospitality',
    category: 'brand-system',
    year: 2024,
    tagline: 'A hospitality brand that moves like light.',
    services: ['Brand Strategy', 'Visual Identity', 'Packaging', 'Signage'],
    featured: true,
    order: 2,
  },
  {
    _id: 'cs-3',
    title: 'Rawaa',
    slug: { current: 'rawaa' },
    client: 'Rawaa Wellness',
    category: 'visual-identity',
    year: 2023,
    tagline: 'Wellness distilled into a visual language.',
    services: ['Brand Identity', 'Art Direction', 'Digital Design'],
    featured: true,
    order: 3,
  },
  {
    _id: 'cs-4',
    title: 'Nour Studios',
    slug: { current: 'nour-studios' },
    client: 'Nour Creative',
    category: 'brand-strategy',
    year: 2023,
    tagline: 'Building a creative infrastructure from scratch.',
    services: ['Brand Strategy', 'Naming', 'Visual Identity'],
    featured: true,
    order: 4,
  },
  {
    _id: 'cs-5',
    title: 'Jbal',
    slug: { current: 'jbal' },
    client: 'Jbal Produce',
    category: 'brand-identity',
    year: 2023,
    tagline: 'Mountain-grown. Minimally told.',
    services: ['Brand Identity', 'Packaging', 'Brand Guidelines'],
    featured: false,
    order: 5,
  },
]

export const mockJournalPosts: JournalPost[] = [
  {
    _id: 'jp-1',
    title: 'The Case for Restraint in Brand Design',
    slug: { current: 'case-for-restraint' },
    publishedAt: '2024-06-10T10:00:00Z',
    category: 'design-thinking',
    excerpt:
      'In a world saturated with stimulation, the most powerful brands are those that know precisely what to leave out.',
    readTime: 6,
    featured: true,
  },
  {
    _id: 'jp-2',
    title: 'What Lebanon Taught Us About Identity',
    slug: { current: 'what-lebanon-taught-us' },
    publishedAt: '2024-04-22T10:00:00Z',
    category: 'culture',
    excerpt:
      'A country that rebuilds itself over and over is one that understands brand resilience better than any business school.',
    readTime: 8,
    featured: true,
  },
  {
    _id: 'jp-3',
    title: 'Beyond the Logo: Building a Complete Brand System',
    slug: { current: 'beyond-the-logo' },
    publishedAt: '2024-02-14T10:00:00Z',
    category: 'process',
    excerpt:
      'The logo is the punctuation mark at the end of a long sentence. Here\'s how we write the rest of it.',
    readTime: 7,
    featured: false,
  },
  {
    _id: 'jp-4',
    title: 'Detect, Define, Design, Deliver',
    slug: { current: 'our-process' },
    publishedAt: '2023-12-01T10:00:00Z',
    category: 'process',
    excerpt:
      'The four-stage process we\'ve developed over years of building brands that last — and why every step matters.',
    readTime: 5,
    featured: false,
  },
]
